# Generated by Django 5.0.4 on 2024-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PelosiTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trade_type', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
                ('trade_date', models.CharField(max_length=100)),
                ('trade_price', models.CharField(max_length=100)),
                ('since_transaction', models.CharField(max_length=100)),
            ],
        ),
    ]
