# Generated by Django 5.0.4 on 2024-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NancyPelosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_worth', models.CharField(max_length=100)),
                ('trade_volume', models.CharField(max_length=100)),
                ('total_trades', models.CharField(max_length=100)),
                ('last_traded', models.CharField(max_length=100)),
            ],
        ),
    ]
