# Generated by Django 5.0.4 on 2024-04-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historicaldata_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='date',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
