# Generated by Django 5.0.4 on 2024-05-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historicaldata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelositrade',
            name='photo_url',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='photo_url',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
